### ISSUE TITLE
Turtle WoW - Water and Air Totem not showing. Totemic Recall breaks addon.

### ISSUE THREAD

**Issue by deanadamfry** [laytya/CallOfElements#2]
The addon displays Earth and Fire totems just fine however, Water and Air totems do not appear at all. There is also a new skill called Totemic Recall which breaks this addon at Level 40.

**Comment by laytya** [comment]
my shaman only 33 =) have to lvl up to fix it =))

**Comment by deanadamfry** [comment]
> 

Ah that explains it, thank you for letting me know you are working on it. Could you please comment on this back when you have fixed it, thank you laytya.

**Comment by McKecksle** [comment]
Would be awsome because i love this addon and it sucks playing without it.

**Comment by Denk21** [comment]
I fixed the totemic issue by checking the element name is either Fire, Earth, Air, Water before assigning it in visual COE_TotemVisuals.Lua file line 195.  You do need to end the whole if at the bottom.  ill add it when I get a chance

if( totem.Element == "Earth" or totem.Element == "Fire" or totem.Element == "Water" or totem.Element == "Air") then
			buttons[totem.Element] = buttons[totem.Element] + 1;

**Comment by laytya** [comment]
bad fix.
I found root of problem... fixed w/ 1 space =) 
later will do release after tests

**Comment by deanadamfry** [comment]
> bad fix. I found root of problem... fixed w/ 1 space =) later will do release after tests

Nice thank you Laytya, will be able to get back into TurtleWoW again once you release that.

**Comment by laytya** [comment]
fixed in https://github.com/laytya/CallOfElements/commit/dd380bcc114a4ec502b697a62d8d5e754dcf26c1
