### ISSUE TITLE
Totem bar not showing

### ISSUE THREAD

**Issue by orlymike** [laytya/CallOfElements#3]
Totem bar not showing, getting 
ERROR:Interface\Addons\CallOfElements\COE_TotemVisual.lua:1116:attempt to index field'?'(a nil value)

Do you need to be level 40 with recall totem to get this version to work?

**Comment by Noeek** [comment]
same error, when I reach lvl 40 and learn my skills then it didn't work anymore.

**Comment by laytya** [comment]
1. install latest version
2. clear old settings by deleting - WoW\WTF\Account\[YOUR ACCOUNT]\Turtle WoW\[YOUR CHAR]\SavedVariables\CallOfElements.lua

**Comment by Noeek** [comment]
> 1. install latest version
> 2. clear old settings by deleting - WoW\WTF\Account[YOUR ACCOUNT]\Turtle WoW[YOUR CHAR]\SavedVariables\CallOfElements.lua

hi, this version works very well in my english client, but found an error when changed to the chinese client.
I noticed that this file "Localization.cn.lua" had a incorrect translation at line 58. 
-----
COESTR_TOTEMICRECALL = "图腾召唤" -- Need translation
the spell "totemic recall" which its chinese translation is "图腾召回"
召回 is means recycle sth, 召唤 is means call sth's name. 
can you fix the translation error.
I've tried it, It works when I changed the translation, you can check it again.
thanks
-----
